version: '3'
services:

  react-web:
    build: ./notes-web
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true
    depends_on: 
      - koa-api

  koa-api:
    build: ./notes-api
    ports:
      - "9000:9000"
    restart: always
    depends_on: 
      - redis-db
    
  redis-db:
    image: redis
    restart: always
