version: '3'
services:

  react-web:
    build: ./notes-web
    ports:
      - "3000:3000"
    restart: always

  koa-api:
    build: ./notes-api
    links:
      - redis-db
    ports:
      - "9000:9000"
    restart: always
    
  redis-db:
    image: redis
    restart: always